initStore([
  {
    id: 0,
    title: 'Elden Ring: Shadow of the Erdtree Edition (PS5/Xbox)',
    description: 'Includes the base game and the Shadow of the Erdtree expansion for an epic open-world RPG adventure.',
    price: 79.99,
    discountPrice: 59.99,
    image: 'img/game-1.jpg',
  },
  {
    id: 1,
    title: 'Grand Theft Auto V: Premium Edition (PS5)',
    description: 'Includes the full GTA V story and access to GTA Online with next-gen enhancements.',
    price: 49.99,
    discountPrice: 29.99,
    image: 'img/game-2.jpg',
  },
  {
    id: 2,
    title: 'Resident Evil 4 Remake (PS5)',
    description: 'Modern reimagining of the survival horror classic with stunning visuals and gameplay.',
    price: 59.99,
    discountPrice: 44.99,
    image: 'img/game-3.jpg',
  },
  {
    id: 3,
    title: 'EA Sports FC 24 (PS5)',
    description: 'The latest football simulation with updated teams, leagues, and HyperMotion technology.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'img/game-4.jpg',
  },
  {
    id: 4,
    title: 'The Last of Us Part I (PS5)',
    description: 'Remake of the award-winning post-apocalyptic adventure with rebuilt visuals and gameplay.',
    price: 79.99,
    discountPrice: 49.99,
    image: 'img/game-5.jpg',
  },
  {
    id: 5,
    title: 'Hogwarts Legacy (PS5/Xbox)',
    description: 'Open-world action RPG set in the Harry Potter universe, explore Hogwarts in the 1800s.',
    price: 69.99,
    discountPrice: 54.99,
    image: 'img/game-6.jpg',
  },
]);
