initStore([
  {
    id: 0,
    title: 'Cyber Odyssey: Nexus Protocol (PC/PS5/Xbox)',
    description: 'A sprawling open-world sci-fi RPG where you uncover a deep conspiracy across multiple planets.',
    price: 79.99,
    discountPrice: 62.99,
    image: 'img/game-1.jpg',
  },
  {
    id: 1,
    title: 'Street Brawl X: Definitive Edition (PS5/Xbox)',
    description: 'A fast-paced urban fighting game with cinematic story mode and online multiplayer tournaments.',
    price: 59.99,
    discountPrice: 42.99,
    image: 'img/game-2.jpg',
  },
  {
    id: 2,
    title: 'Darkspire Chronicles (PC/PS5)',
    description: 'Fantasy action-adventure with a rich storyline, brutal combat, and vast dungeons to explore.',
    price: 69.99,
    discountPrice: 54.99,
    image: 'img/game-3.jpg',
  },
  {
    id: 3,
    title: 'Galaxy Racer: Quantum Drift (PC/PS5/Xbox)',
    description: 'High-speed interstellar racing game with customizable ships and breathtaking cosmic tracks.',
    price: 64.99,
    discountPrice: 49.99,
    image: 'img/game-4.jpg',
  },
  {
    id: 4,
    title: 'Legends of Valoria: Reforged (PC/PS5)',
    description: 'Remastered epic fantasy RPG featuring enhanced graphics, orchestral soundtrack, and new quests.',
    price: 74.99,
    discountPrice: 57.99,
    image: 'img/game-5.jpg',
  },
  {
    id: 5,
    title: 'Mech Assault Prime (PC/PS5/Xbox)',
    description: 'Futuristic mech combat game with destructible environments and intense 5v5 multiplayer battles.',
    price: 69.99,
    discountPrice: 53.99,
    image: 'img/game-6.jpg',
  },
]);
